language: go
sudo: false

go:
  - 1.x
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - npm install -g yarn

install:
  - make bootstrap

script:
  - make analyse
  - make cover
  - make release

deploy:
  provider: releases
  api_key:
    secure: HKTaQHYxn917CgpJfRzYISSHvp7DGGox26D8KH8EVKEWUUbS6RxDb3otZXl7WD5DZXmZufwShPYgqTogv1mktbtFL2AIbffrCGWwZw4oH1ve0V52n8JSOp8ah+tCL8Fijk9ZEAU7SzWlXcUeWeKCVj17XNEjs8h2x+4zaXeJyOK/lBv44vwGzC9HanV5RKyrn0AIa89wtrBCBJuQ1k2gi858k+IXuGeN3Hz/72NDrj2AcKKssxG4jfNBhVD3tSfxQc5g/7i53aOk0vWFg5izMlqAYuhsLZfeon/q5GjT6Fv1hrAdRoKf47NR0uKCbN/7ebSTeELr5apTS8YwQhgvBMNWIfPH4Hm0l8IfYzfYvhwhEfgCnSB7xQYspjfYdQvfBAMdqxvQ4A4kvdEII1aFnhqMWGTvvHrBNuac2tpG33iVUONXfEqR/xh88FA6wlQ1ReC5sRfsr2quE6HBm4tIvMHBGhiSh+Hp3PV2+qsjc51vUUrOpVeu07oMAsd+HGrZedrj25kaPE26iO/89jllY7yYkmbwwpujme6CgAycMcMjBcrXbYttd0naJhIVAuGvsrTzjuiST8qHO/DSvfP09hcsGyGxYq5w0O+hEYxAW1/Dky7gpviGxtrbgMAvPoq/H1eI3QIr3bFQWzj+fim5ywbtHGpxVF3zOiAb2Plqz/U=
  skip_cleanup: true
  on:
    tags: true
  file:
    - build/web-template-linux-amd64
    - build/web-template-linux-amd64.md5
    - build/web-template-linux-amd64.sha256
    - build/web-template-windows-amd64
    - build/web-template-windows-amd64.md5
    - build/web-template-windows-amd64.sha256
    - build/web-template-darwin-amd64
    - build/web-template-darwin-amd64.md5
    - build/web-template-darwin-amd64.sha256
