language: go
sudo: false

go:
  - 1.x
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - npm install -g yarn

install:
  - make bootstrap

script:
  - make release

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_APIKEY
  skip_cleanup: true
  on:
    tags: true
  file:
    - build/web-template-linux-amd64
    - build/web-template-linux-amd64.md5
    - build/web-template-linux-amd64.sha256
    - build/web-template-windows-amd64
    - build/web-template-windows-amd64.md5
    - build/web-template-windows-amd64.sha256
    - build/web-template-darwin-amd64
    - build/web-template-darwin-amd64.md5
    - build/web-template-darwin-amd64.sha256
